services:
  postgres:
    image: 'postgres'
    container_name: db_postgres
    restart: 'always'
    ports:
      - '6543:5432'
    volumes: 
      - ./dockerInits/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 'admin'
  firebird:
    image: 'jacobalberty/firebird:v2.5.9-sc'
    container_name: db_firebird
    restart: 'always'
    ports:
      - '3355:3050'
    environment:
      FIREBIRD_DATABASE: 'test'
      ISC_PASSWORD: 'masterkey'
    volumes:
      - ./dockerInits/TPSOCKETS.DB:/firebird/data/TPSOCKETS.DB
  mysql:
    image: mysql
    container_name: db_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes: 
      - ./dockerInits/MySqlInit.sql:/docker-entrypoint-initdb.d/MySqlInit.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
  switch:
    build: '.'
    restart: 'always'
    ports:
      - '3000:3000'
    environment:
      DATABASE_PGHOST: postgres
      DATABASE_FBHOST: firebird
      DATABASE_MSHOST: mysql
